-- MySQL Script generated by MySQL Workbench
-- Tue Oct  8 15:52:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema recetas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema recetas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recetas` DEFAULT CHARACTER SET utf8 ;
USE `recetas` ;

-- -----------------------------------------------------
-- Table `recetas`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recetas`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `alias` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recetas`.`Recetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recetas`.`Recetas` (
  `idReceta` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(1000) NOT NULL,
  `es_postre` INT NULL,
  `es_saludable` INT NULL,
  `es_bebida` INT NULL,
  `es_sopa` INT NULL,
  `tiempo` DATE NULL,
  PRIMARY KEY (`idReceta`),
  UNIQUE INDEX `idReceta_UNIQUE` (`idReceta` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recetas`.`Usuario_has_Recetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recetas`.`Usuario_has_Recetas` (
  `Usuario_idUsuario` INT NOT NULL,
  `Recetas_idReceta` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Recetas_idReceta`),
  INDEX `fk_Usuario_has_Recetas_Recetas1_idx` (`Recetas_idReceta` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Recetas_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Recetas_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `recetas`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Recetas_Recetas1`
    FOREIGN KEY (`Recetas_idReceta`)
    REFERENCES `recetas`.`Recetas` (`idReceta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
